version: '3.8'
services:
    neo4j:
        image: neo4j:5-community
        container_name: worldbuild_neo4j
        ports:
            - "7474:7474" # HTTP
            - "7687:7687" # Bolt
        volumes:
            - neo4j_data:/data
        environment:
            - NEO4J_AUTH=neo4j/${NEO4J_PASSWORD}
        restart: unless-stopped

    meilisearch:
        image: getmeili/meilisearch:latest
        container_name: worldbuild_meili
        ports:
            - "7700:7700"
        volumes:
            - meili_data:/meili_data
        environment:
            - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}
        restart: unless-stopped

volumes:
    neo4j_data:
    meili_data:
